var dir_ba0a5884162be49ca564693d469c3119 =
[
    [ "saf_utilities.h", "saf__utilities_8h.html", "saf__utilities_8h" ],
    [ "saf_utility_bessel.c", "saf__utility__bessel_8c.html", "saf__utility__bessel_8c" ],
    [ "saf_utility_bessel.h", "saf__utility__bessel_8h.html", "saf__utility__bessel_8h" ],
    [ "saf_utility_complex.c", "saf__utility__complex_8c.html", null ],
    [ "saf_utility_complex.h", "saf__utility__complex_8h.html", null ],
    [ "saf_utility_decor.c", "saf__utility__decor_8c.html", "saf__utility__decor_8c" ],
    [ "saf_utility_decor.h", "saf__utility__decor_8h.html", "saf__utility__decor_8h" ],
    [ "saf_utility_error.c", "saf__utility__error_8c.html", "saf__utility__error_8c" ],
    [ "saf_utility_error.h", "saf__utility__error_8h.html", "saf__utility__error_8h" ],
    [ "saf_utility_fft.c", "saf__utility__fft_8c.html", "saf__utility__fft_8c" ],
    [ "saf_utility_fft.h", "saf__utility__fft_8h.html", "saf__utility__fft_8h" ],
    [ "saf_utility_filters.c", "saf__utility__filters_8c.html", "saf__utility__filters_8c" ],
    [ "saf_utility_filters.h", "saf__utility__filters_8h.html", "saf__utility__filters_8h" ],
    [ "saf_utility_geometry.c", "saf__utility__geometry_8c.html", "saf__utility__geometry_8c" ],
    [ "saf_utility_geometry.h", "saf__utility__geometry_8h.html", "saf__utility__geometry_8h" ],
    [ "saf_utility_latticeCoeffs.c", "saf__utility__lattice_coeffs_8c.html", "saf__utility__lattice_coeffs_8c" ],
    [ "saf_utility_loudspeaker_presets.c", "saf__utility__loudspeaker__presets_8c.html", "saf__utility__loudspeaker__presets_8c" ],
    [ "saf_utility_loudspeaker_presets.h", "saf__utility__loudspeaker__presets_8h.html", "saf__utility__loudspeaker__presets_8h" ],
    [ "saf_utility_matrixConv.c", "saf__utility__matrix_conv_8c.html", "saf__utility__matrix_conv_8c" ],
    [ "saf_utility_matrixConv.h", "saf__utility__matrix_conv_8h.html", "saf__utility__matrix_conv_8h" ],
    [ "saf_utility_misc.c", "saf__utility__misc_8c.html", "saf__utility__misc_8c" ],
    [ "saf_utility_misc.h", "saf__utility__misc_8h.html", "saf__utility__misc_8h" ],
    [ "saf_utility_pitch.c", "saf__utility__pitch_8c.html", "saf__utility__pitch_8c" ],
    [ "saf_utility_pitch.h", "saf__utility__pitch_8h.html", "saf__utility__pitch_8h" ],
    [ "saf_utility_qmf.c", "saf__utility__qmf_8c.html", "saf__utility__qmf_8c" ],
    [ "saf_utility_qmf.h", "saf__utility__qmf_8h.html", "saf__utility__qmf_8h" ],
    [ "saf_utility_sensorarray_presets.c", "saf__utility__sensorarray__presets_8c.html", "saf__utility__sensorarray__presets_8c" ],
    [ "saf_utility_sensorarray_presets.h", "saf__utility__sensorarray__presets_8h.html", "saf__utility__sensorarray__presets_8h" ],
    [ "saf_utility_sort.c", "saf__utility__sort_8c.html", "saf__utility__sort_8c" ],
    [ "saf_utility_sort.h", "saf__utility__sort_8h.html", "saf__utility__sort_8h" ],
    [ "saf_utility_veclib.c", "saf__utility__veclib_8c.html", "saf__utility__veclib_8c" ],
    [ "saf_utility_veclib.h", "saf__utility__veclib_8h.html", "saf__utility__veclib_8h" ]
];