var searchData=
[
  ['saf_5ffft_5fdata_2653',['saf_fft_data',['../structsaf__fft__data.html',1,'']]],
  ['saf_5frfft_5fdata_2654',['saf_rfft_data',['../structsaf__rfft__data.html',1,'']]],
  ['saf_5fsofa_5fcontainer_2655',['saf_sofa_container',['../structsaf__sofa__container.html',1,'']]],
  ['saf_5fsort_5fdouble_2656',['saf_sort_double',['../structsaf__sort__double.html',1,'']]],
  ['saf_5fsort_5ffloat_2657',['saf_sort_float',['../structsaf__sort__float.html',1,'']]],
  ['saf_5fsort_5fint_2658',['saf_sort_int',['../structsaf__sort__int.html',1,'']]],
  ['saf_5fstft_5fdata_2659',['saf_stft_data',['../structsaf__stft__data.html',1,'']]],
  ['safmatconv_5fdata_2660',['safMatConv_data',['../structsaf_mat_conv__data.html',1,'']]],
  ['safmulconv_5fdata_2661',['safMulConv_data',['../structsaf_mul_conv__data.html',1,'']]],
  ['sldoa_5fdata_2662',['sldoa_data',['../structsldoa__data.html',1,'']]],
  ['smb_5fpitchshift_5fdata_2663',['smb_pitchShift_data',['../structsmb__pitch_shift__data.html',1,'']]],
  ['speexresamplerstate_5f_2664',['SpeexResamplerState_',['../struct_speex_resampler_state__.html',1,'']]],
  ['sphesprit_5fdata_2665',['sphESPRIT_data',['../structsph_e_s_p_r_i_t__data.html',1,'']]],
  ['sphmusic_5fdata_2666',['sphMUSIC_data',['../structsph_m_u_s_i_c__data.html',1,'']]],
  ['sphpwd_5fdata_2667',['sphPWD_data',['../structsph_p_w_d__data.html',1,'']]],
  ['spreader_5fdata_2668',['spreader_data',['../structspreader__data.html',1,'']]]
];
